### PR TITLE
Bug/master/issue63

### LINKED ISSUE #63: pljava does not compile on mac osx ver 10.11.1 and postgres 9.4
Hi 

If this is not the right place to post these issues I beg you pardon.

Here is my question:

I haven't been able to compile on mac os el capitan and postgres 9.4

 this is the postgres version I have

 PostgreSQL 9.4.4 on x86_64-apple-darwin, compiled by i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00), 64-bit

And this is what i get after running mvn install .

```
[ERROR]   "_textout", referenced from:
[ERROR]       _getAS in Function.o
[ERROR]   "_unknownrecv", referenced from:
[ERROR]       _UDT_receive in UDT.o
[ERROR]   "_unknownsend", referenced from:
[ERROR]       _UDT_send in UDT.o
[ERROR] ld: symbol(s) not found for architecture x86_64
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] PostgreSQL PL/Java ................................. SUCCESS [  1.479 s]
[INFO] PL/Java API ........................................ SUCCESS [  2.126 s]
[INFO] PL/Java backend Java code .......................... SUCCESS [  3.218 s]
[INFO] PL/Java backend native code ........................ FAILURE [ 11.206 s]
[INFO] PL/Java Deploy ..................................... SKIPPED
[INFO] PL/Java Ant tasks .................................. SKIPPED
[INFO] PL/Java examples ................................... SKIPPED
[INFO] PL/Java packaging .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.199 s
[INFO] Finished at: 2015-11-06T05:11:14+01:00
[INFO] Final Memory: 27M/368M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.maven-nar:nar-maven-plugin:3.1.0:nar-compile (default-nar-compile) on project pljava-so: NAR: Compile failed: g++ failed with return code 1 -> [Help 1]
```

Am I doing something wrong?

Regards.

Daniel

### PR DESCRIPTION
**Pull request by jcflack**
Fixes #63 by declaring the `nar` artifact to be of `plugin` type rather than `shared`, so on OS X it is allowed to have unresolved references that will be found in the thing that loads it.

On non-OS X platforms, the choice of `plugin` or `shared` makes no difference in the link. It does, however, show up in the pathname of the built object, so the wiki install instructions will have to be updated.

Tested by me, dblanch, Darsstar.

### CODE REVIEW

**Comment by jcflack** [comment]
Closing this PR to reopen from rebased bug/master/issue63rb1.
